version: '3.1'
services:
  stats-server:
    build: ewm-stats-service/stat-server
    image: explore-with-me-stats-server
    container_name: stats_server_container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewmStatsService
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "9090:9090"
      - "8081:8081"
    depends_on:
      - stats-db
  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmStatsService
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  ewm-service:
    build: ewm-service
    image: explore-with-me-ewm-service
    container_name: ewm_service_container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/evmService
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - NAME_SERVICE=http://stats-server:9090
    ports:
      - "8080:8080"
      - "8089:8089"
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=evmService
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
